[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "alma_spectral_line"
version = "0.0.2"
readme = "README.md"

dependencies = [
"sjmm_util",
"astropy",
"numpy",
"interferopy"
"pandas"
]